const REPORTS_KEY='laudoEmDia.reports.v1',SETTINGS_KEY='laudoEmDia.settings.v1';
const seedReports=[
 {id:'escola-padre-geraldo',title:'Escola Padre Geraldo',unit:'Secretaria de Educação',address:'Rua Duque de Caxias, Mamanguape/PB',inspectionDate:'2026-07-08',completedDate:'2026-07-08',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Laudo com 9 páginas.',published:true,pdfPath:'assets/pdfs/escola-padre-geraldo.pdf',pdfName:'Laudo de Locação - Escola Padre Geraldo.pdf',updatedAt:'2026-07-08T14:37:00'},
 {id:'secretaria-industria',title:'Secretaria de Indústria e Comércio',unit:'Secretaria de Indústria e Comércio',address:'Rua Duque de Caxias, Mamanguape/PB',inspectionDate:'2026-07-03',completedDate:'2026-07-12',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Laudo com 9 páginas.',published:true,pdfPath:'assets/pdfs/secretaria-industria-comercio.pdf',pdfName:'Laudo de Locação - Secretaria de Indústria e Comércio.pdf',updatedAt:'2026-07-12T23:11:00'},
 {id:'posto-guarda-pitanga',title:'Posto da Guarda de Pitanga da Estrada',unit:'Segurança Comunitária',address:'Rua do Campo, Pitanga da Estrada, Zona Rural, Mamanguape/PB',inspectionDate:'2026-07-08',completedDate:'2026-07-10',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Posto Integrado de Segurança Comunitária. Laudo com 8 páginas.',published:true,pdfPath:'assets/pdfs/posto-guarda-pitanga.pdf',pdfName:'Laudo de Locação - Posto da Guarda de Pitanga.pdf',updatedAt:'2026-07-10T16:41:00'},
 {id:'assistencia-social',title:'Secretaria de Assistência Social',unit:'Secretaria de Assistência Social',address:'Travessa Dr. Ariosvaldo Rodrigues da Costa, nº 77, Centro, Mamanguape/PB',inspectionDate:'2026-07-01',completedDate:'2026-07-02',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Laudo com 12 páginas.',published:true,pdfPath:'assets/pdfs/assistencia-social.pdf',pdfName:'Laudo de Locação - Assistência Social.pdf',updatedAt:'2026-07-02T22:52:00'},
 {id:'caps-ad',title:'CAPS AD',unit:'Secretaria de Saúde',address:'Rua Genésio de Andrade, Mamanguape/PB',inspectionDate:'2026-07-01',completedDate:'2026-07-02',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Centro de Atenção Psicossocial Álcool e Drogas. Laudo com 12 páginas.',published:true,pdfPath:'assets/pdfs/caps-ad.pdf',pdfName:'Laudo de Locação - CAPS AD.pdf',updatedAt:'2026-07-02T21:04:00'},
 {id:'ubs-xua',title:'UBS Xuá Mendonça',unit:'Secretaria de Saúde',address:'Sítio Mendonça, s/n, Zona Rural, Mamanguape/PB',inspectionDate:'2026-06-02',completedDate:'2026-07-10',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Unidade Básica de Saúde. Laudo com 10 páginas.',published:true,pdfPath:'assets/pdfs/ubs-xua.pdf',pdfName:'Laudo de Locação - UBS Xuá.pdf',updatedAt:'2026-07-10T16:58:00'}
];
const defaultSettings={startDay:30,deadline:'',organization:'Prefeitura Municipal de Mamanguape',publicMessage:'Consulte a situação, a última atualização e os documentos publicados.'};
let reports=load(REPORTS_KEY,seedReports),settings=load(SETTINGS_KEY,defaultSettings),activeView='gestao',adminSession=null,cloudReady=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){if(!v)return 'Não informada';return new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(v+'T12:00:00Z'))}
function fmtTime(v){if(!v)return '—';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}
function slug(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function initials(v){return v.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function statusClass(v){return slug(v)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
function cloudStatus(message,state=''){const el=$('#cloudStatus');el.textContent=message;el.className=`cloud-status ${state}`}
function mapRow(r){return {id:r.id,protocol:r.protocol||'',title:r.title,unit:r.unit,address:r.address,inspectionDate:r.inspection_date||'',completedDate:r.completed_date||'',deliveryDate:r.delivery_date||'',status:r.status,progress:r.progress,responsible:r.responsible||'',crea:r.crea||'',notes:r.notes||'',published:r.published,pdfPath:r.pdf_url||'',pdfName:r.pdf_name||'',requesterName:r.requester_name||'',requesterEmail:r.requester_email||'',requesterPhone:r.requester_phone||'',source:r.source,createdAt:r.created_at,updatedAt:r.updated_at}}
function toRow(r){return {title:r.title,unit:r.unit,address:r.address,inspection_date:r.inspectionDate||null,completed_date:r.completedDate||null,delivery_date:r.deliveryDate||null,status:r.status,progress:r.progress,responsible:r.responsible||null,crea:r.crea||null,notes:r.notes||null,published:r.published}}
function persist(){if(!cloudReady)localStorage.setItem(REPORTS_KEY,JSON.stringify(reports));renderAll()}
function setView(view){activeView=view;$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const p=new URLSearchParams();if(view==='publico')p.set('publico','1');if(adminSession)p.set('admin','1');history.replaceState(null,'',location.pathname+(p.size?'?'+p:''));window.scrollTo({top:0,behavior:'smooth'})}
function renderMetrics(){const total=reports.length,done=reports.filter(x=>['Concluído','Entregue'].includes(x.status)).length,review=reports.filter(x=>x.status==='Em revisão').length,pending=total-done;$('#metrics').innerHTML=[['Σ',total,'Total de laudos'],['↻',pending,'Em andamento'],['✓',done,'Concluídos'],['⌁',review,'Aguardando revisão']].map(x=>`<div class="metric"><span class="metric-icon">${x[0]}</span><span><strong>${x[1]}</strong><small>${x[2]}</small></span></div>`).join('')}
function filteredReports(){const q=$('#search').value.trim().toLowerCase(),status=$('#statusFilter').value;return reports.filter(r=>(!status||r.status===status)&&(!q||[r.title,r.unit,r.address].join(' ').toLowerCase().includes(q)))}
function renderList(){const list=filteredReports();$('#emptyState').classList.toggle('hidden',list.length>0);$('#reportList').innerHTML=list.map(r=>`<article class="report-row"><div class="report-main"><span class="report-letter">${esc(initials(r.title))}</span><span><strong>${esc(r.title)}</strong><small>${esc(r.address)}</small></span></div><div class="report-cell"><strong>${esc(r.unit)}</strong><small>Vistoria: ${fmtDate(r.inspectionDate)}</small></div><div class="report-cell"><span class="status ${statusClass(r.status)}">${esc(r.status)}</span><small>Atualizado ${fmtTime(r.updatedAt)}</small></div><div class="report-cell progress-cell"><strong>${r.progress}%</strong><div class="progress-track"><div class="progress-bar" style="width:${r.progress}%"></div></div></div><button class="more" data-open="${esc(r.id)}" aria-label="Abrir ${esc(r.title)}">›</button></article>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>showDetail(b.dataset.open))}
function renderPublic(){const list=reports.filter(x=>x.published),done=list.filter(x=>['Concluído','Entregue'].includes(x.status)).length;$('#publicMessage').textContent=settings.publicMessage;$('#publicSummary').innerHTML=`<span><strong>${list.length}</strong> laudos publicados</span><span><strong>${done}</strong> concluídos</span><span>Órgão: <strong>${esc(settings.organization)}</strong></span>`;$('#publicGrid').innerHTML=list.map(r=>`<article class="public-card"><div class="public-card-top"><span class="report-letter">${esc(initials(r.title))}</span><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></div><h3>${esc(r.title)}</h3><div class="address">${esc(r.address)}</div><div class="progress-track"><div class="progress-bar" style="width:${r.progress}%"></div></div><footer><small>Atualizado<br><strong>${fmtTime(r.updatedAt)}</strong></small><button class="text-button" data-public-open="${esc(r.id)}">Ver laudo →</button></footer></article>`).join('');$$('[data-public-open]').forEach(b=>b.onclick=()=>showDetail(b.dataset.publicOpen,true))}
function renderDeadline(){const d=settings.deadline;$('#deadlineLabel').textContent=d?`Dia 30 até ${fmtDate(d)}`:`A partir do dia ${settings.startDay}`;if(!d){$('#deadlineHint').textContent='Defina a data final em Configurações';return}const days=Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000);$('#deadlineHint').textContent=days<0?`Prazo encerrado há ${Math.abs(days)} dia(s)`:days===0?'O prazo termina hoje':`Faltam ${days} dia(s)`}
function renderAll(){renderMetrics();renderList();renderPublic();renderDeadline()}
function applyAccessMode(){const isAdmin=!!adminSession;document.body.classList.toggle('admin-mode',isAdmin);document.body.classList.toggle('public-mode',!isAdmin);$('#adminAccess').textContent=isAdmin?'Sair':'Acesso administrativo';if(isAdmin){cloudStatus('Online · administrador','online');if(activeView==='publico'&&!location.search.includes('publico=1'))setView('gestao')}else{cloudStatus(cloudReady?'Online':'Conectando…',cloudReady?'online':'');setView('publico')}window.dispatchEvent(new CustomEvent('laudo:auth',{detail:{isAdmin}}))}
async function reloadReports(){try{const token=adminSession?.access_token;const rows=await LaudoCloud.listReports(token);reports=rows.map(mapRow);cloudReady=true;cloudStatus(token?'Online · administrador':'Online','online');renderAll()}catch(error){cloudReady=false;cloudStatus('Sem conexão','error');renderAll();toast('Não foi possível atualizar os laudos online') }}
function openForm(id){if(!adminSession){$('#loginDialog').showModal();return}$('#reportForm').reset();$('#reportId').value='';$('#formTitle').textContent='Novo laudo';$('#deleteReport').classList.add('hidden');$('#responsible').value='Bruno Rodrigues Xaxier';$('#crea').value='2118287402';$('#published').checked=true;$('#progress').value=0;$('#progressOutput').textContent='0%';$('#currentPdf').textContent='';if(id){const r=reports.find(x=>x.id===id);if(!r)return;$('#formTitle').textContent='Editar laudo';$('#reportId').value=r.id;['title','unit','address','inspectionDate','completedDate','deliveryDate','status','progress','responsible','crea','notes'].forEach(k=>$('#'+k).value=r[k]??'');$('#published').checked=!!r.published;$('#progressOutput').textContent=r.progress+'%';$('#currentPdf').textContent=r.pdfName?`Atual: ${r.pdfName}`:'';$('#deleteReport').classList.remove('hidden')}$('#reportDialog').showModal()}
function safeFileName(name){const dot=name.lastIndexOf('.'),ext=dot>=0?name.slice(dot).toLowerCase():'',base=dot>=0?name.slice(0,dot):name;return slug(base).slice(0,80)+ext}
async function saveReport(e){e.preventDefault();if(!adminSession){$('#reportDialog').close();$('#loginDialog').showModal();return}const submit=e.submitter;submit.disabled=true;submit.textContent='Salvando…';try{const id=$('#reportId').value,existing=reports.find(x=>x.id===id);let item={...existing,title:$('#title').value.trim(),unit:$('#unit').value.trim(),address:$('#address').value.trim(),inspectionDate:$('#inspectionDate').value,completedDate:$('#completedDate').value,deliveryDate:$('#deliveryDate').value,status:$('#status').value,progress:+$('#progress').value,responsible:$('#responsible').value.trim(),crea:$('#crea').value.trim(),notes:$('#notes').value.trim(),published:$('#published').checked};let row=existing?await LaudoCloud.updateReport(existing.id,toRow(item),adminSession.access_token):await LaudoCloud.createReport(toRow(item),adminSession.access_token);const pdf=$('#pdfFile').files[0];if(pdf){const path=`${row.id}/${Date.now()}-${safeFileName(pdf.name)}`;await LaudoCloud.upload('reports-public',path,pdf,adminSession.access_token);row=await LaudoCloud.updateReport(row.id,{pdf_url:LaudoCloud.publicFileUrl('reports-public',path),pdf_name:pdf.name},adminSession.access_token);await LaudoCloud.addAttachment({report_id:row.id,kind:'pdf',storage_path:path,file_name:pdf.name,mime_type:pdf.type,is_public:item.published},adminSession.access_token)}for(const file of [...$('#photoFiles').files]){const path=`${row.id}/fotos/${Date.now()}-${crypto.randomUUID()}-${safeFileName(file.name)}`;await LaudoCloud.upload('reports-public',path,file,adminSession.access_token);await LaudoCloud.addAttachment({report_id:row.id,kind:'photo',storage_path:path,file_name:file.name,mime_type:file.type,is_public:item.published},adminSession.access_token)}await reloadReports();$('#reportDialog').close();toast('Laudo salvo online com sucesso')}catch(error){toast('Erro ao salvar: '+error.message)}finally{submit.disabled=false;submit.textContent='Salvar laudo'}}
async function showDetail(id,isPublic=false){
  const r=reports.find(x=>x.id===id);if(!r)return;
  $('#detailUnit').textContent=r.unit;$('#detailTitle').textContent=r.title;
  let photoUrls=[];
  if(adminSession){try{const files=await LaudoCloud.listAttachments(id,adminSession.access_token);const photos=files.filter(x=>x.kind==='photo');photoUrls=await Promise.all(photos.map(x=>{const privateRequestPhoto=r.protocol&&x.storage_path.startsWith(`${r.id}/${r.protocol}/`);return privateRequestPhoto?LaudoCloud.signedFileUrl('requests-private',x.storage_path,adminSession.access_token):LaudoCloud.publicFileUrl('reports-public',x.storage_path)}))}catch{}}
  $('#detailContent').innerHTML=`<div class="detail-grid"><div class="detail-item"><small>Situação</small><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></div><div class="detail-item"><small>Progresso</small><strong>${r.progress}%</strong></div><div class="detail-item"><small>Endereço</small><strong>${esc(r.address)}</strong></div><div class="detail-item"><small>Vistoria</small><strong>${fmtDate(r.inspectionDate)}</strong></div><div class="detail-item"><small>Conclusão</small><strong>${fmtDate(r.completedDate)}</strong></div><div class="detail-item"><small>Responsável</small><strong>${esc(r.responsible||'Não informado')}${r.crea?` · CREA ${esc(r.crea)}`:''}</strong></div></div>${r.notes?`<p>${esc(r.notes)}</p>`:''}<div class="detail-actions">${r.pdfName?'<button class="primary" id="openPdf">Abrir arquivo</button>':''}${adminSession&&!isPublic?'<button class="secondary" id="editDetail">Editar cadastro</button>':''}</div>${photoUrls.length?`<div class="gallery">${photoUrls.map(url=>`<img src="${esc(url)}" alt="Foto do imóvel">`).join('')}</div>`:''}`;
  if(r.pdfName)$('#openPdf').onclick=()=>openPdf(r);if(adminSession&&!isPublic)$('#editDetail').onclick=()=>{$('#detailDialog').close();openForm(id)};$('#detailDialog').showModal()
}
function openPdf(r){if(r.pdfPath){window.open(r.pdfPath,'_blank','noopener');return}toast('PDF ainda não foi publicado')}

$$('.nav-button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#newReport').onclick=()=>openForm();$('#reportForm').onsubmit=saveReport;$('#progress').oninput=e=>$('#progressOutput').textContent=e.target.value+'%';$('#search').oninput=renderList;$('#statusFilter').onchange=renderList;
$('#deleteReport').onclick=async()=>{const id=$('#reportId').value;if(!id||!confirm('Excluir este cadastro e seus anexos?'))return;try{await LaudoCloud.deleteReport(id,adminSession.access_token);await reloadReports();$('#reportDialog').close();toast('Cadastro excluído')}catch(error){toast('Não foi possível excluir: '+error.message)}};
$('#copyPublicLink').onclick=async()=>{const url=location.href.split('?')[0]+'?publico=1';try{await navigator.clipboard.writeText(url);toast('Link copiado')}catch{prompt('Copie o link:',url)}};
function fillSettings(){$('#startDay').value=settings.startDay;$('#deadline').value=settings.deadline;$('#organization').value=settings.organization;$('#publicMessageInput').value=settings.publicMessage}fillSettings();
$('#saveSettings').onclick=()=>{settings={startDay:+$('#startDay').value||30,deadline:$('#deadline').value,organization:$('#organization').value.trim(),publicMessage:$('#publicMessageInput').value.trim()};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));renderAll();toast('Configurações salvas neste computador')};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),settings,reports},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-laudos-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=()=>toast('A importação direta ficará disponível em uma atualização futura. O banco online já mantém os registros.')
$$('[data-login-close]').forEach(b=>b.onclick=()=>$('#loginDialog').close());
$('#adminAccess').onclick=async()=>{if(adminSession){if(confirm('Deseja sair da área administrativa?')){LaudoCloud.signOut();adminSession=null;applyAccessMode();await reloadReports()}}else $('#loginDialog').showModal()};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='Entrando…';$('#loginError').classList.add('hidden');try{adminSession=await LaudoCloud.signIn($('#loginEmail').value.trim(),$('#loginPassword').value);$('#loginDialog').close();applyAccessMode();setView('gestao');await reloadReports();toast('Acesso administrativo liberado')}catch(error){$('#loginError').textContent='Não foi possível entrar. Confira o e-mail e a senha.';$('#loginError').classList.remove('hidden')}finally{button.disabled=false;button.textContent='Entrar'}};

async function initialize(){renderAll();adminSession=await LaudoCloud.session();applyAccessMode();await reloadReports();if(location.search.includes('admin=1')&&!adminSession)$('#loginDialog').showModal()}
initialize();navigator.storage?.persist?.();
