const REPORTS_KEY='laudoEmDia.reports.v1', SETTINGS_KEY='laudoEmDia.settings.v1';
const seedReports=[
 {id:'escola-padre-geraldo',title:'Escola Padre Geraldo',unit:'Secretaria de Educação',address:'Rua Duque de Caxias, Mamanguape/PB',inspectionDate:'2026-07-08',completedDate:'2026-07-08',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Laudo com 9 páginas.',published:true,pdfPath:'assets/pdfs/escola-padre-geraldo.pdf',pdfName:'Laudo de Locação - Escola Padre Geraldo.pdf',updatedAt:'2026-07-08T14:37:00'},
 {id:'secretaria-industria',title:'Secretaria de Indústria e Comércio',unit:'Secretaria de Indústria e Comércio',address:'Rua Duque de Caxias, Mamanguape/PB',inspectionDate:'2026-07-03',completedDate:'2026-07-12',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Laudo com 9 páginas.',published:true,pdfPath:'assets/pdfs/secretaria-industria-comercio.pdf',pdfName:'Laudo de Locação - Secretaria de Indústria e Comércio.pdf',updatedAt:'2026-07-12T23:11:00'},
 {id:'posto-guarda-pitanga',title:'Posto da Guarda de Pitanga da Estrada',unit:'Segurança Comunitária',address:'Rua do Campo, Pitanga da Estrada, Zona Rural, Mamanguape/PB',inspectionDate:'2026-07-08',completedDate:'2026-07-10',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Posto Integrado de Segurança Comunitária. Laudo com 8 páginas.',published:true,pdfPath:'assets/pdfs/posto-guarda-pitanga.pdf',pdfName:'Laudo de Locação - Posto da Guarda de Pitanga.pdf',updatedAt:'2026-07-10T16:41:00'},
 {id:'assistencia-social',title:'Secretaria de Assistência Social',unit:'Secretaria de Assistência Social',address:'Travessa Dr. Ariosvaldo Rodrigues da Costa, nº 77, Centro, Mamanguape/PB',inspectionDate:'2026-07-01',completedDate:'2026-07-02',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Laudo com 12 páginas.',published:true,pdfPath:'assets/pdfs/assistencia-social.pdf',pdfName:'Laudo de Locação - Assistência Social.pdf',updatedAt:'2026-07-02T22:52:00'},
 {id:'caps-ad',title:'CAPS AD',unit:'Secretaria de Saúde',address:'Rua Genésio de Andrade, Mamanguape/PB',inspectionDate:'2026-07-01',completedDate:'2026-07-02',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Centro de Atenção Psicossocial Álcool e Drogas. Laudo com 12 páginas.',published:true,pdfPath:'assets/pdfs/caps-ad.pdf',pdfName:'Laudo de Locação - CAPS AD.pdf',updatedAt:'2026-07-02T21:04:00'},
 {id:'ubs-xua',title:'UBS Xuá Mendonça',unit:'Secretaria de Saúde',address:'Sítio Mendonça, s/n, Zona Rural, Mamanguape/PB',inspectionDate:'2026-06-02',completedDate:'2026-07-10',deliveryDate:'',status:'Concluído',progress:100,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:'Unidade Básica de Saúde. Laudo com 10 páginas.',published:true,pdfPath:'assets/pdfs/ubs-xua.pdf',pdfName:'Laudo de Locação - UBS Xuá.pdf',updatedAt:'2026-07-10T16:58:00'}
];
const defaultSettings={startDay:30,deadline:'',organization:'Prefeitura Municipal de Mamanguape',publicMessage:'Consulte a situação, a última atualização e os documentos publicados.'};
let reports=load(REPORTS_KEY,seedReports),settings=load(SETTINGS_KEY,defaultSettings),activeView='gestao';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}}
function persist(){localStorage.setItem(REPORTS_KEY,JSON.stringify(reports));renderAll()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){if(!v)return 'Não informada';return new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(v+'T12:00:00Z'))}
function fmtTime(v){if(!v)return '—';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}
function slug(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function initials(v){return v.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function statusClass(v){return slug(v)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function setView(view){activeView=view;$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(view==='publico')history.replaceState(null,'',location.pathname+'?publico=1');else history.replaceState(null,'',location.pathname);window.scrollTo({top:0,behavior:'smooth'})}
function renderMetrics(){const total=reports.length,done=reports.filter(x=>['Concluído','Entregue'].includes(x.status)).length,review=reports.filter(x=>x.status==='Em revisão').length,pending=total-done;$('#metrics').innerHTML=[['Σ',total,'Total de laudos'],['↻',pending,'Em andamento'],['✓',done,'Concluídos'],['⌁',review,'Aguardando revisão']].map(x=>`<div class="metric"><span class="metric-icon">${x[0]}</span><span><strong>${x[1]}</strong><small>${x[2]}</small></span></div>`).join('')}
function filteredReports(){const q=$('#search').value.trim().toLowerCase(),status=$('#statusFilter').value;return reports.filter(r=>(!status||r.status===status)&&(!q||[r.title,r.unit,r.address].join(' ').toLowerCase().includes(q)))}
function renderList(){const list=filteredReports();$('#emptyState').classList.toggle('hidden',list.length>0);$('#reportList').innerHTML=list.map(r=>`<article class="report-row"><div class="report-main"><span class="report-letter">${esc(initials(r.title))}</span><span><strong>${esc(r.title)}</strong><small>${esc(r.address)}</small></span></div><div class="report-cell"><strong>${esc(r.unit)}</strong><small>Vistoria: ${fmtDate(r.inspectionDate)}</small></div><div class="report-cell"><span class="status ${statusClass(r.status)}">${esc(r.status)}</span><small>Atualizado ${fmtTime(r.updatedAt)}</small></div><div class="report-cell progress-cell"><strong>${r.progress}%</strong><div class="progress-track"><div class="progress-bar" style="width:${r.progress}%"></div></div></div><button class="more" data-open="${esc(r.id)}" aria-label="Abrir ${esc(r.title)}">›</button></article>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>showDetail(b.dataset.open))}
function renderPublic(){const list=reports.filter(x=>x.published),done=list.filter(x=>['Concluído','Entregue'].includes(x.status)).length;$('#publicMessage').textContent=settings.publicMessage;$('#publicSummary').innerHTML=`<span><strong>${list.length}</strong> laudos publicados</span><span><strong>${done}</strong> concluídos</span><span>Órgão: <strong>${esc(settings.organization)}</strong></span>`;$('#publicGrid').innerHTML=list.map(r=>`<article class="public-card"><div class="public-card-top"><span class="report-letter">${esc(initials(r.title))}</span><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></div><h3>${esc(r.title)}</h3><div class="address">${esc(r.address)}</div><div class="progress-track"><div class="progress-bar" style="width:${r.progress}%"></div></div><footer><small>Atualizado<br><strong>${fmtTime(r.updatedAt)}</strong></small><button class="text-button" data-public-open="${esc(r.id)}">Ver laudo →</button></footer></article>`).join('');$$('[data-public-open]').forEach(b=>b.onclick=()=>showDetail(b.dataset.publicOpen,true))}
function renderDeadline(){const d=settings.deadline;$('#deadlineLabel').textContent=d?`Dia 30 até ${fmtDate(d)}`:`A partir do dia ${settings.startDay}`;if(!d){$('#deadlineHint').textContent='Defina a data final em Configurações';return}const days=Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000);$('#deadlineHint').textContent=days<0?`Prazo encerrado há ${Math.abs(days)} dia(s)`:days===0?'O prazo termina hoje':`Faltam ${days} dia(s)`}
function renderAll(){renderMetrics();renderList();renderPublic();renderDeadline()}
function openForm(id){$('#reportForm').reset();$('#reportId').value='';$('#formTitle').textContent='Novo laudo';$('#deleteReport').classList.add('hidden');$('#responsible').value='Bruno Rodrigues Xaxier';$('#crea').value='2118287402';$('#published').checked=true;$('#progress').value=0;$('#progressOutput').textContent='0%';$('#currentPdf').textContent='';if(id){const r=reports.find(x=>x.id===id);if(!r)return;$('#formTitle').textContent='Editar laudo';$('#reportId').value=r.id;['title','unit','address','inspectionDate','completedDate','deliveryDate','status','progress','responsible','crea','notes'].forEach(k=>$('#'+k).value=r[k]??'');$('#published').checked=!!r.published;$('#progressOutput').textContent=r.progress+'%';$('#currentPdf').textContent=r.pdfName?`Atual: ${r.pdfName}`:'';$('#deleteReport').classList.remove('hidden')}$('#reportDialog').showModal()}
async function saveReport(e){e.preventDefault();const oldId=$('#reportId').value,existing=reports.find(x=>x.id===oldId);const id=oldId||slug($('#title').value)+'-'+Date.now().toString().slice(-5);const r={...existing,id,title:$('#title').value.trim(),unit:$('#unit').value.trim(),address:$('#address').value.trim(),inspectionDate:$('#inspectionDate').value,completedDate:$('#completedDate').value,deliveryDate:$('#deliveryDate').value,status:$('#status').value,progress:+$('#progress').value,responsible:$('#responsible').value.trim(),crea:$('#crea').value.trim(),notes:$('#notes').value.trim(),published:$('#published').checked,updatedAt:new Date().toISOString()};const pdf=$('#pdfFile').files[0];if(pdf){await dbPut(id+':pdf',pdf);r.pdfName=pdf.name;r.pdfPath='';r.hasUploadedPdf=true}const photos=[...$('#photoFiles').files];for(const file of photos)await dbPut(`${id}:photo:${Date.now()}:${crypto.randomUUID()}`,file);if(photos.length)r.photoCount=(r.photoCount||0)+photos.length;if(existing)reports=reports.map(x=>x.id===id?r:x);else reports.unshift(r);persist();$('#reportDialog').close();toast('Laudo salvo com sucesso')}
async function showDetail(id,isPublic=false){const r=reports.find(x=>x.id===id);if(!r)return;$('#detailUnit').textContent=r.unit;$('#detailTitle').textContent=r.title;const photos=await dbList(id+':photo:');$('#detailContent').innerHTML=`<div class="detail-grid"><div class="detail-item"><small>Situação</small><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></div><div class="detail-item"><small>Progresso</small><strong>${r.progress}%</strong></div><div class="detail-item"><small>Endereço</small><strong>${esc(r.address)}</strong></div><div class="detail-item"><small>Vistoria</small><strong>${fmtDate(r.inspectionDate)}</strong></div><div class="detail-item"><small>Conclusão</small><strong>${fmtDate(r.completedDate)}</strong></div><div class="detail-item"><small>Responsável</small><strong>${esc(r.responsible||'Não informado')}${r.crea?` · CREA ${esc(r.crea)}`:''}</strong></div></div>${r.notes?`<p>${esc(r.notes)}</p>`:''}<div class="detail-actions">${r.pdfName?'<button class="primary" id="openPdf">Abrir PDF</button>':''}${!isPublic?'<button class="secondary" id="editDetail">Editar cadastro</button>':''}</div>${photos.length?`<div class="gallery">${photos.map(x=>`<img src="${URL.createObjectURL(x.value)}" alt="Foto do imóvel">`).join('')}</div>`:''}`;if(r.pdfName)$('#openPdf').onclick=()=>openPdf(r);if(!isPublic)$('#editDetail').onclick=()=>{$('#detailDialog').close();openForm(id)};$('#detailDialog').showModal()}
async function openPdf(r){if(r.pdfPath){window.open(r.pdfPath,'_blank');return}const file=await dbGet(r.id+':pdf');if(!file){toast('Arquivo PDF não encontrado neste navegador');return}window.open(URL.createObjectURL(file),'_blank')}
function openDb(){return new Promise((resolve,reject)=>{const q=indexedDB.open('laudoEmDiaFiles',1);q.onupgradeneeded=()=>q.result.createObjectStore('files');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function dbPut(key,value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function dbGet(key){const db=await openDb();return new Promise((resolve,reject)=>{const q=db.transaction('files').objectStore('files').get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function dbList(prefix){const db=await openDb();return new Promise((resolve,reject)=>{const out=[];const q=db.transaction('files').objectStore('files').openCursor();q.onsuccess=()=>{const c=q.result;if(!c){resolve(out);return}if(String(c.key).startsWith(prefix))out.push({key:c.key,value:c.value});c.continue()};q.onerror=()=>reject(q.error)})}
$$('.nav-button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#newReport').onclick=()=>openForm();$('#reportForm').onsubmit=saveReport;$('#progress').oninput=e=>$('#progressOutput').textContent=e.target.value+'%';$('#search').oninput=renderList;$('#statusFilter').onchange=renderList;
$('#deleteReport').onclick=()=>{const id=$('#reportId').value;if(confirm('Excluir este cadastro? Os arquivos enviados neste navegador não serão recuperados.')){reports=reports.filter(x=>x.id!==id);persist();$('#reportDialog').close();toast('Cadastro excluído')}};
$('#copyPublicLink').onclick=async()=>{const url=location.href.split('?')[0]+'?publico=1';try{await navigator.clipboard.writeText(url);toast('Link copiado')}catch{prompt('Copie o link:',url)}};
function fillSettings(){$('#startDay').value=settings.startDay;$('#deadline').value=settings.deadline;$('#organization').value=settings.organization;$('#publicMessageInput').value=settings.publicMessage}fillSettings();
$('#saveSettings').onclick=()=>{settings={startDay:+$('#startDay').value||30,deadline:$('#deadline').value,organization:$('#organization').value.trim(),publicMessage:$('#publicMessageInput').value.trim()};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));renderAll();toast('Configurações salvas')};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),settings,reports},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-laudos-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.reports))throw Error();if(confirm('Substituir os cadastros atuais pelos dados do backup?')){reports=data.reports;settings={...defaultSettings,...data.settings};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));fillSettings();persist();toast('Backup importado')}}catch{toast('Arquivo de backup inválido')}};
if(location.search.includes('publico=1'))setView('publico');renderAll();navigator.storage?.persist?.();
