let notifications=[];
const requestDialog=$('#requestDialog'),protocolDialog=$('#protocolDialog'),notificationsDialog=$('#notificationsDialog');
function renderNotifications(){const unread=notifications.filter(n=>!n.is_read).length;$('#notificationCount').textContent=unread;$('#notificationCount').classList.toggle('hidden',unread===0);$('#notificationsList').innerHTML=notifications.length?notifications.map(n=>`<div class="notification-item ${n.is_read?'':'unread'}"><strong>${esc(n.title)}</strong><span>${esc(n.message)}</span><small>${fmtTime(n.created_at)}</small></div>`).join(''):'<div class="empty"><strong>Nenhuma notificação.</strong></div>'}
async function loadNotifications(){if(!adminSession){notifications=[];renderNotifications();return}try{notifications=await LaudoCloud.listNotifications(adminSession.access_token);renderNotifications()}catch{notifications=[];renderNotifications()}}
$('#requestReport').onclick=()=>requestDialog.showModal();$$('[data-request-close]').forEach(b=>b.onclick=()=>requestDialog.close());$$('[data-protocol-close]').forEach(b=>b.onclick=()=>protocolDialog.close());$$('[data-notifications-close]').forEach(b=>b.onclick=()=>notificationsDialog.close());
$('#openNotifications').onclick=async()=>{await loadNotifications();notificationsDialog.showModal();try{await LaudoCloud.markNotificationsRead(adminSession.access_token);notifications=notifications.map(n=>({...n,is_read:true}));renderNotifications()}catch{}};
$('#requestForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='Enviando…';const photos=[...$('#requestPhotos').files];try{const result=await LaudoCloud.submitRequest({p_requester_name:$('#requesterName').value.trim(),p_requester_email:$('#requesterEmail').value.trim(),p_requester_phone:$('#requesterPhone').value.trim(),p_unit:$('#requesterUnit').value.trim(),p_building_name:$('#buildingName').value.trim(),p_address:$('#requestAddress').value.trim(),p_notes:$('#requestNotes').value.trim()||null});let photoWarning=false;for(const file of photos){try{const path=`${result.report_id}/${result.protocol}/${Date.now()}-${crypto.randomUUID()}-${safeFileName(file.name)}`;await LaudoCloud.upload('requests-private',path,file);await LaudoCloud.registerRequestPhoto({p_report_id:result.report_id,p_protocol:result.protocol,p_storage_path:path,p_file_name:file.name,p_mime_type:file.type})}catch{photoWarning=true}}requestDialog.close();e.target.reset();$('#protocolNumber').textContent=result.protocol;protocolDialog.showModal();await reloadReports();if(photoWarning)toast('Solicitação salva, mas uma foto não pôde ser enviada')}catch(error){toast('Não foi possível enviar: '+error.message)}finally{button.disabled=false;button.textContent='Enviar solicitação'}};
$('#copyProtocol').onclick=async()=>{const value=$('#protocolNumber').textContent;try{await navigator.clipboard.writeText(value);toast('Protocolo copiado')}catch{prompt('Copie o protocolo:',value)}};
const baseShowDetail=showDetail;showDetail=async function(id,isPublic=false){await baseShowDetail(id,isPublic);const r=reports.find(x=>x.id===id);if(r?.protocol){const box=document.createElement('div');box.className='detail-item request-meta';box.innerHTML=`<small>Protocolo</small><strong>${esc(r.protocol)}</strong>${adminSession&&r.requesterName?`<small>Solicitante: ${esc(r.requesterName)} · ${esc(r.requesterEmail)} ${r.requesterPhone?'· '+esc(r.requesterPhone):''}</small>`:''}`;$('#detailContent .detail-grid').prepend(box)}};
window.addEventListener('laudo:auth',loadNotifications);renderNotifications();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{});
