const NOTIFICATIONS_KEY='laudoEmDia.notifications.v1';
let notifications=load(NOTIFICATIONS_KEY,[]);
const requestDialog=$('#requestDialog'),protocolDialog=$('#protocolDialog'),notificationsDialog=$('#notificationsDialog');
function saveNotifications(){localStorage.setItem(NOTIFICATIONS_KEY,JSON.stringify(notifications));renderNotifications()}
function addNotification(message,reportId,audience='admin'){notifications.unshift({id:crypto.randomUUID(),message,reportId,audience,read:false,createdAt:new Date().toISOString()});saveNotifications()}
function renderNotifications(){const admin=notifications.filter(n=>n.audience==='admin'),unread=admin.filter(n=>!n.read).length;$('#notificationCount').textContent=unread;$('#notificationCount').classList.toggle('hidden',unread===0);$('#notificationsList').innerHTML=admin.length?admin.map(n=>`<div class="notification-item ${n.read?'':'unread'}"><strong>${esc(n.message)}</strong><small>${fmtTime(n.createdAt)}</small></div>`).join(''):'<div class="empty"><strong>Nenhuma notificação.</strong></div>'}
$('#requestReport').onclick=()=>requestDialog.showModal();$$('[data-request-close]').forEach(b=>b.onclick=()=>requestDialog.close());$$('[data-protocol-close]').forEach(b=>b.onclick=()=>protocolDialog.close());$$('[data-notifications-close]').forEach(b=>b.onclick=()=>notificationsDialog.close());
$('#openNotifications').onclick=()=>{notifications.filter(n=>n.audience==='admin').forEach(n=>n.read=true);saveNotifications();notificationsDialog.showModal()};
$('#requestForm').onsubmit=async e=>{e.preventDefault();const protocol=`LED-${new Date().getFullYear()}-${Math.random().toString().slice(2,8)}`;const id='solicitacao-'+Date.now();const name=$('#requesterName').value.trim(),title=$('#buildingName').value.trim(),photos=[...$('#requestPhotos').files];const report={id,title,unit:$('#requesterUnit').value.trim(),address:$('#requestAddress').value.trim(),inspectionDate:'',completedDate:'',deliveryDate:'',status:'Solicitado',progress:0,responsible:'Bruno Rodrigues Xaxier',crea:'2118287402',notes:$('#requestNotes').value.trim(),published:true,updatedAt:new Date().toISOString(),protocol,requesterName:name,requesterEmail:$('#requesterEmail').value.trim(),requesterPhone:$('#requesterPhone').value.trim(),source:'public-request',photoCount:photos.length};for(const file of photos)await dbPut(`${id}:photo:${Date.now()}:${crypto.randomUUID()}`,file);reports.unshift(report);persist();addNotification(`${name} solicitou um novo laudo: ${title}.`,id);requestDialog.close();e.target.reset();$('#protocolNumber').textContent=protocol;protocolDialog.showModal()};
$('#copyProtocol').onclick=async()=>{const value=$('#protocolNumber').textContent;try{await navigator.clipboard.writeText(value);toast('Protocolo copiado')}catch{prompt('Copie o protocolo:',value)}};
const baseShowDetail=showDetail;showDetail=async function(id,isPublic=false){await baseShowDetail(id,isPublic);const r=reports.find(x=>x.id===id);if(r?.protocol){const box=document.createElement('div');box.className='detail-item request-meta';box.innerHTML=`<small>Protocolo</small><strong>${esc(r.protocol)}</strong>${!isPublic?`<small>Solicitante: ${esc(r.requesterName)} · ${esc(r.requesterEmail)} ${r.requesterPhone?'· '+esc(r.requesterPhone):''}</small>`:''}`;$('#detailContent .detail-grid').prepend(box)}};
const baseSaveReport=$('#reportForm').onsubmit;$('#reportForm').onsubmit=async e=>{const id=$('#reportId').value,before=reports.find(x=>x.id===id),oldStatus=before?.status;await baseSaveReport(e);const after=reports.find(x=>x.id===id);if(after?.requesterEmail&&oldStatus!==after.status&&['Concluído','Entregue'].includes(after.status)){addNotification(`O laudo ${after.title} foi ${after.status.toLowerCase()}. Avisar ${after.requesterName} em ${after.requesterEmail}.`,id,'admin')}};
const onlinePublic=location.hostname.endsWith('github.io');
if(location.search.includes('publico=1')||onlinePublic){document.body.classList.add('public-mode');if(onlinePublic)setView('publico')}
if(onlinePublic)$('#requestReport').onclick=()=>alert('O formulário de solicitação online será ativado depois da conexão com o banco de dados. Por enquanto, esta página permite acompanhar e baixar os laudos.');
renderNotifications();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{});
